
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - internal

  backend:
    build:
      context: ./projects/dev-backend/anime-dataset
    image: behamot007/dev-backend:latest
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-3000}
      - DATASET_PATH=${BACKEND_DATASET_PATH:-/app/dataset/characters.jsonl}
      - API_TOKEN=${BACKEND_API_TOKEN:-}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
    volumes:
      - ./projects/dev-backend/anime-dataset/dataset:/app/dataset
    networks:
      - internal
    expose:
      - "${BACKEND_PORT:-3000}"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        DEV_SERVER_NAME: ${DEV_SERVER_NAME:-dev.localhost}
        WWW_SERVER_NAME: ${WWW_SERVER_NAME:-www.localhost}
    image: behamot007/anime-frontend:latest
    depends_on:
      - backend
      - twitch-controller
    environment:
      - BACKEND_API_BASE=${FRONTEND_BACKEND_API_BASE:-http://backend:3000}
      - DEV_SERVER_NAME=${DEV_SERVER_NAME:-dev.localhost}
      - WWW_SERVER_NAME=${WWW_SERVER_NAME:-www.localhost}
    volumes:
      - ./server/certbot/www:/var/www/certbot
    ports:
      - "8080:80"
    networks:
      - internal
      - public

  twitch-controller:
    build:
      context: ./projects/dev-backend/twitch-chat-controller
    image: behamot007/twitch-chat-controller:latest
    environment:
      - NODE_ENV=production
      - PORT=4010
      - TWITCH_API_PASSWORD=${TWITCH_API_PASSWORD:-}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:-}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET:-}
      - TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI:-https://www.behamot.de/services/twitch-bot/oauth/callback}
      - TWITCH_BOT_USERNAME=${TWITCH_BOT_USERNAME:-}
      - TWITCH_BOT_OAUTH_TOKEN=${TWITCH_BOT_OAUTH_TOKEN:-}
      - TWITCH_DEFAULT_CHANNEL=${TWITCH_DEFAULT_CHANNEL:-}
    networks:
      - internal
    expose:
      - "4010"
    ports:
      - "4010:4010"

  certbot:
    image: certbot/certbot:latest
    profiles:
      - certbot
    volumes:
      - ./server/certbot/etc-letsencrypt:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c"]
    command: "trap exit TERM; while :; do sleep 3600; done"

networks:
  internal:
    driver: bridge
  public:
    driver: bridge

volumes:
  postgres_data:
    driver: local
